README.md, packages/cli/package.json
- Update Readme
- Update README.md
=> doc: Docs Update 📑

.github/workflows/build-api.yaml, .github/workflows/build-cli.yaml, packages/api/controllers/apikey.controller.ts, packages/api/dbdump/dump.sql, packages/api/package.json, packages/api/routes/apikey.routes.ts, packages/api/services/apikey.service.ts, packages/cli/package.json, packages/cli/src/commands/config.ts, packages/cli/src/commands/gist.ts, packages/cli/src/commands/index.ts, packages/cli/src/commands/upload.ts, packages/cli/src/commands/urlShrink.ts, packages/cli/src/functions/config.ts, packages/cli/src/functions/gist.ts, packages/cli/src/functions/info.ts, packages/cli/src/functions/shrink.ts, packages/cli/src/functions/upload.ts, packages/cli/src/libs/axios.ts, packages/cli/src/shx.ts, packages/cli/tsconfig.json
=> working on cli promptts

packages/api/controllers/apikey.controller.ts, packages/api/controllers/gists.controller.ts, packages/api/controllers/info.controller.ts, packages/api/controllers/upload.controller.ts, packages/api/controllers/urlstore.controller.ts, packages/api/data/uploader.service.ts, packages/api/graphql/schema.graphql, packages/api/hasura/metadata/databases/databases.yaml, packages/api/hasura/migrations/default/1684991758327_alter_table_public_uploads_add_column_deleteToken/down.sql, packages/api/hasura/migrations/default/1684991758327_alter_table_public_uploads_add_column_deleteToken/up.sql, packages/api/package.json, packages/api/routes/gist.routes.ts, packages/api/routes/info.routes.ts, packages/api/routes/upload.routes.ts, packages/api/routes/url.routes.ts, packages/api/services/gist.service.ts, packages/api/services/info.service.ts, packages/api/services/upload.service.ts, packages/api/services/urlstore.service.ts
- 🎗:: Added Management Services + Routes
- 🦚: added sys info details
=> Adding Management routes + System Info

.github/workflows/eslint.yml, .github/workflows/todo.yaml
- Fixes GH Action Eslint Bug
- Added TODO GH Actions
=> Fixes GH Actions

.github/CODEOWNERS, .github/FUNDING.yml, .github/pr-badge.yml, .github/pr-branch-labeler.yml, .github/workflows/apply-done-label.yaml, .github/workflows/auto-tag-pr.yaml, .github/workflows/pr-labeler.yaml, .github/workflows/wiki-docs-sync.yaml, docs/hello.md, package.json, packages/api/package.json, packages/cli/package.json, packages/dashboard/package.json
- Worked over new release + actions 🚂
- CODEOWNER Changes
=> GH Updates

packages/api/controllers/apikey.controller.ts, packages/api/libs/utilities.ts, packages/api/services/apikey.service.ts
**Category**: Refactoring Only
**Overview**
- Added Data Secrecy to List API Key endpoint
- Reworked API Key deletion
**Issue Number** #36 
**Code Quality Checklist**
=> 🛅: Added API Key encap + Reworked on API Key Delete Methods

packages/api/helpers/upload.factory.ts
**Category**: 
Refactoring Only
**Overview**
> Added Upload File name sanitation
**Issue Number** #34
=> 🧼: Sanitize File Name

packages/api/controllers/config.controller.ts, packages/api/helpers/cache.factory.ts, packages/api/helpers/upload.factory.ts, packages/api/index.ts, packages/api/interfaces/config.interface.d.ts, packages/api/routes/settings.routes.ts, packages/api/services/config.service.ts, packages/api/services/upload.service.ts
**Category**: 
- Feature
- Refactoring
**Overview**
- Added Settings API
- Added Dync File Ext Whitelist
**Issue Number** #28
=> ⚙️: Added `settings` api

packages/api/helpers/cache.factory.ts, packages/api/helpers/gql_clent.ts, packages/api/index.ts, packages/api/libs/customErrHandler.ts, packages/api/libs/utilities.ts, packages/api/package.json, packages/api/routes/index.ts, packages/api/services/config.service.ts, packages/api/services/upload.service.ts, yarn.lock
**Category**: 
Feature
**Overview**
- Added winston logger
**Issue Number** #32
=> 📢: Added winston logger

packages/api/configs/index.ts, packages/api/controllers/gists.controller.ts, packages/api/interfaces/message.enums.ts, packages/api/libs/middleware.ts, packages/api/routes/apikey.routes.ts, packages/api/routes/gist.routes.ts, packages/api/routes/settings.routes.ts, packages/api/routes/upload.routes.ts, packages/api/routes/url.routes.ts, packages/api/validators/apikey.validation.ts, packages/api/validators/gist.validation.ts, packages/api/validators/settings.validation.ts, packages/api/validators/upload.validation.ts, packages/api/validators/url.validation.ts
**Category**: 
Feature
**Overview**
- Worked on input validations using joi.
**Issue Number** #33 
**New Vars**
- Use `yarn watch` to build errors live while development.
=> 🧩: Added Joi Validation Support

.github/workflows/sonal-ql.yaml, .licrc, sonar-project.properties
**Category**: 
Build related changes
**Overview**
> Added SonalQL for Code Analysis
=> GH: Added Sonal QL Support for Code Analysis

.github/labeler.yml, .github/workflows/build-dashboard.yaml, .github/workflows/build-discord-bot.yaml, .github/workflows/test-builds-bot.yaml, packages/discord/Dockerfile, packages/discord/docker-compose.yaml
**Category**: Feature
**Overview**
- Added File Upload via Discord Bot
**New Vars**
- @packages/discord contains discord
- Check the contained .env.example for ENV required for running Discord Bot
- `yarn dev` for running bot in development mode
=> Discord Bot as supporting Endpoint

packages/dashboard/app/(dashboard)/dashboard/apiKeys/page.tsx, packages/dashboard/app/(dashboard)/dashboard/notes/page.tsx, packages/dashboard/app/(dashboard)/dashboard/uploads/page.tsx, packages/dashboard/components/Lists/ApiKeyList/index.tsx, packages/dashboard/lib/sidebar.ts
[![chirag3003](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/chirag3003/f73ae6)](https://github.com/chirag3003) ![Medium](https://badgen.net/badge/PR%20Size/Medium/f3ff59) [![chirag3003 /feature/api-key-gen → BRAVO68WEB/shx](https://badgen.net/badge/%2369/chirag3003%20%2Ffeature%2Fapi-key-gen%20%E2%86%92%20BRAVO68WEB%2Fshx/ab5afc)](https://github.com/BRAVO68WEB/shx/tree/feature/api-key-gen) ![Commits: 4 | Files Changed: 5 | Additions: 87](https://badgen.net/badge/New%20Code/Commits%3A%204%20%7C%20Files%20Changed%3A%205%20%7C%20Additions%3A%2087/dddd00) ![Unchecked Tasks](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FNotice/Unchecked%20Tasks/f25265) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb- …
=> Added ui for api key list

packages/dashboard/components/Lists/ApiKeyList/index.tsx
[![chirag3003](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/chirag3003/f73ae6)](https://github.com/chirag3003) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![chirag3003 /feature/api-key-gen → BRAVO68WEB/shx](https://badgen.net/badge/%2371/chirag3003%20%2Ffeature%2Fapi-key-gen%20%E2%86%92%20BRAVO68WEB%2Fshx/ab5afc)](https://github.com/BRAVO68WEB/shx/tree/feature/api-key-gen) ![Commits: 1 | Files Changed: 1 | Additions: 5](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%205/dddd00) ![Category](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Category/f25265) ![Unchecked Tasks](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FNotice/Unchecked%20Tasks/f25265) [<img width="16" alt="Powered by Pull Request Badge" …
=> added demo data

packages/dashboard/.eslintrc.json, packages/dashboard/app/(dashboard)/dashboard/url/page.tsx, packages/dashboard/components/Lists/ShortenUrlList/URLControls.tsx, packages/dashboard/components/Lists/ShortenUrlList/index.tsx, packages/dashboard/components/ui/Input.tsx, packages/dashboard/lib/sidebar.ts
[![chirag3003](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/chirag3003/f73ae6)](https://github.com/chirag3003) ![Medium](https://badgen.net/badge/PR%20Size/Medium/f3ff59) [![chirag3003 /feature/url-shortener → BRAVO68WEB/shx](https://badgen.net/badge/%2373/chirag3003%20%2Ffeature%2Furl-shortener%20%E2%86%92%20BRAVO68WEB%2Fshx/ab5afc)](https://github.com/BRAVO68WEB/shx/tree/feature/url-shortener) ![Commits: 5 | Files Changed: 6 | Additions: 197](https://badgen.net/badge/New%20Code/Commits%3A%205%20%7C%20Files%20Changed%3A%206%20%7C%20Additions%3A%20197/dddd00) ![Unchecked Tasks](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FNotice/Unchecked%20Tasks/f25265) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85 …
=> added new page for url shortener

packages/dashboard/app/(dashboard)/dashboard/utilities/instance-info/page.tsx, packages/dashboard/lib/sidebar.ts
[![chirag3003](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/chirag3003/f73ae6)](https://github.com/chirag3003) ![Medium](https://badgen.net/badge/PR%20Size/Medium/f3ff59) [![chirag3003 /issue-75-Instance_Info_Section → BRAVO68WEB/shx](https://badgen.net/badge/%2383/chirag3003%20%2Fissue-75-Instance_Info_Section%20%E2%86%92%20BRAVO68WEB%2Fshx/ab5afc)](https://github.com/BRAVO68WEB/shx/tree/issue-75-Instance_Info_Section) ![Commits: 4 | Files Changed: 2 | Additions: 17](https://badgen.net/badge/New%20Code/Commits%3A%204%20%7C%20Files%20Changed%3A%202%20%7C%20Additions%3A%2017/dddd00) ![Unchecked Tasks](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FNotice/Unchecked%20Tasks/f25265) [<img width="16" alt="Powered by Pull Request Badge" …
=> Issue 75 instance info section

packages/dashboard/app/(dashboard)/dashboard/utilities/download-config/page.tsx
[![chirag3003](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/chirag3003/f73ae6)](https://github.com/chirag3003) ![Medium](https://badgen.net/badge/PR%20Size/Medium/f3ff59) [![chirag3003 /feature/download-config-ui → BRAVO68WEB/shx](https://badgen.net/badge/%2385/chirag3003%20%2Ffeature%2Fdownload-config-ui%20%E2%86%92%20BRAVO68WEB%2Fshx/ab5afc)](https://github.com/BRAVO68WEB/shx/tree/feature/download-config-ui) ![Commits: 2 | Files Changed: 1 | Additions: 37](https://badgen.net/badge/New%20Code/Commits%3A%202%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%2037/dddd00) ![Unchecked Tasks](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FNotice/Unchecked%20Tasks/f25265) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/11121652 …
=> Feature/download config UI

packages/api/services/gist.service.ts, packages/api/validators/gist.validation.ts
**Category**: Bugfix
**Overview**
_These happened because of invalid Joi config_
- BUG 1:- GET /gist -> Set default page to 1 insted of 0
- BUG 2:- POST /gist -> isPrivate was not whitelisted as a parameter.
**Issue Number**: #90
=> Bug Fix for #90

.vscode/settings.json, packages/discord/src/events/message-create.ts, sonar-project.properties
[![BRAVO68WEB /chore-fixes → BRAVO68WEB/shx](https://badgen.net/badge/%2392/BRAVO68WEB%20%2Fchore-fixes%20%E2%86%92%20BRAVO68WEB%2Fshx/ab5afc)](https://github.com/BRAVO68WEB/shx/tree/chore-fixes) ![Commits: 1 | Files Changed: 3 | Additions: 8](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%203%20%7C%20Additions%3A%208/dddd00) ![Category](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Category/f25265) ![Overview](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Overview/f25265) ![Quality Checklist](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Quality%20Checklist/f25265) ![Incomplete](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FDescription/Incomplete/f25265) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) [<img width="16" …
=> chores fixes

packages/api/dbdump/dump.sql, packages/api/graphql/schema.graphql, packages/api/graphql/types.ts, packages/api/libs/utilities.ts, packages/api/package.json, packages/api/services/apikey.service.ts, yarn.lock
**Category**: Feature
**Overview**
- API Keys now show when they were last used
**Issue Number** _(if applicable)_ #93
**New Vars**
- Updated SQL DUMP with `last_used` in apikeys table.
- `yarn generate:types:gql` now converts gql schema to typescript types.
**Code Quality Checklist**
=> feat: Added API Key last used attribute in API

packages/api/configs/index.ts, packages/api/data/uploader.service.ts, packages/api/helpers/cache.factory.ts, packages/api/helpers/gql_clent.ts, packages/api/index.ts, packages/api/interfaces/config.interface.d.ts, packages/api/libs/middleware.ts, packages/api/package.json, packages/api/services/apikey.service.ts, packages/api/services/upload.service.ts, yarn.lock
**Category**: Feature
**Overview**
- Uses zod to parse and use config env variables.
**Issue Number**: #48 
**New Vars** _(if applicable)_
- Now use `zod` to use env vars
=> feat: use zod to read and parse config

package.json, packages/cli/tsconfig.json, yarn.lock
**Category**: Version Bumps
**Overview**
- Deps updates
**Code Quality Checklist**
=> chore(bump): update dependencies

packages/api/validators/apikey.validation.ts, packages/api/validators/gist.validation.ts, packages/api/validators/settings.validation.ts, packages/api/validators/upload.validation.ts, packages/api/validators/url.validation.ts
**Category**:- Bugfix
**Overview**
- Fix joi erros
**Issue Number**:- #90 (related) 
=> PatchFix for Joi errors

packages/api/services/info.service.ts
**Category**: Refactoring Only
**Overview**
- modified sys info api
**Issue Number** #103
=> ⚙ modified sys info api
